'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import dynamic from 'next/dynamic';
import {Smartphone,LayoutDashboard,ClipboardList,Users,Package,MonitorSmartphone,Truck,Wallet,ChartNoAxesCombined,Settings as SettingsIcon,ShieldCheck,Bell,LogOut,Menu,X,PanelLeftClose,PanelLeftOpen,Plus,ChevronRight} from 'lucide-react';
import {post,roleNames} from '../lib/api';import {usePreference} from '../lib/preferences';import {clearViewMemory} from '../lib/use-query';import {parseRoute,routeHash,type AppRoute} from '../lib/navigation';
import GlobalSearch from './GlobalSearch';import {Empty,PageSkeleton,ToastRegion,toast,Button} from './ui';
const loading=()=> <PageSkeleton/>;
const Dashboard=dynamic(()=>import('./Dashboard'),{loading});const OrdersList=dynamic(()=>import('./OrdersList'),{loading});const Catalog=dynamic(()=>import('./Catalog'),{loading});const OrderDetail=dynamic(()=>import('./OrderDetail'),{loading});const Reports=dynamic(()=>import('./Reports'),{loading});const Settings=dynamic(()=>import('./Settings'),{loading});const NewOrder=dynamic(()=>import('./NewOrder'));
const labels:Record<string,string>={dashboard:'Visão geral',orders:'Ordens de serviço',detail:'Detalhes da OS',customers:'Clientes',devices:'Aparelhos',screens:'Preços de telas',products:'Estoque',suppliers:'Fornecedores',payments:'Pagamentos',reports:'Relatórios',users:'Equipe',audit:'Auditoria',notifications:'Notificações',stock:'Movimentações de estoque',settings:'Configurações'};
const adminViews=new Set(['products','suppliers','payments','reports','users','audit','stock']);
export default function App({user,logout}:{user:any;logout:()=>void}){
 const [route,setRoute]=useState<AppRoute>({view:'dashboard',id:''}),[denied,setDenied]=useState(''),[newOrder,setNewOrder]=useState(false),[mobile,setMobile]=useState(false),[loggingOut,setLoggingOut]=useState(false);
 const [collapsed,setCollapsed]=usePreference('sidebar-collapsed',false,'local');const sidebar=useRef<HTMLElement>(null);const menuButton=useRef<HTMLButtonElement>(null);const content=useRef<HTMLElement>(null);
 const isDenied=useCallback((next:AppRoute)=>user.role!=='ADMIN'&&adminViews.has(next.view),[user.role]);
 const navigate=useCallback((next:AppRoute)=>{if(isDenied(next)){setDenied(next.view);next={view:'dashboard',id:''};window.history.replaceState({},'',routeHash(next))}else setDenied('');setRoute(next);setMobile(false);const hash=routeHash(next);if(window.location.hash!==hash)window.history.pushState({},'',hash);requestAnimationFrame(()=>{content.current?.querySelector<HTMLElement>('h1')?.focus({preventScroll:true});window.scrollTo({top:0,behavior:'instant'})})},[isDenied]);
 useEffect(()=>{const sync=()=>{const next=parseRoute(window.location.hash);if(isDenied(next)){setDenied(next.view);setRoute({view:'dashboard',id:''});window.history.replaceState({},'',routeHash({view:'dashboard',id:''}))}else{setDenied('');setRoute(next)}setMobile(false)};sync();window.addEventListener('popstate',sync);window.addEventListener('hashchange',sync);return()=>{window.removeEventListener('popstate',sync);window.removeEventListener('hashchange',sync)}},[isDenied]);
 useEffect(()=>{const exit=()=>{clearViewMemory();logout()};const nav=(e:Event)=>{const detail=(e as CustomEvent).detail;navigate(typeof detail==='string'?{view:detail,id:''}:detail)};window.addEventListener('oled:logout',exit);window.addEventListener('oled:navigate',nav);return()=>{window.removeEventListener('oled:logout',exit);window.removeEventListener('oled:navigate',nav)}},[logout,navigate]);
 useEffect(()=>{const key=(e:KeyboardEvent)=>{const target=e.target as HTMLElement;if((e.ctrlKey||e.metaKey)&&e.altKey&&e.key.toLowerCase()==='n'&&!document.querySelector('dialog[open]')){e.preventDefault();setNewOrder(true)}if(e.key==='Escape'&&mobile)setMobile(false)};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key)},[mobile]);
 useEffect(()=>{if(!mobile)return;const previous=document.activeElement as HTMLElement;const old=document.body.style.overflow;document.body.style.overflow='hidden';sidebar.current?.querySelector<HTMLButtonElement>('button')?.focus();const trap=(e:KeyboardEvent)=>{if(e.key!=='Tab')return;const controls=Array.from(sidebar.current?.querySelectorAll<HTMLButtonElement>('button')||[]).filter(el=>el.offsetParent!==null);const first=controls[0],last=controls.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus()}};document.addEventListener('keydown',trap);return()=>{document.body.style.overflow=old;document.removeEventListener('keydown',trap);previous?.focus()}},[mobile]);
 useEffect(()=>{document.title=`${labels[route.view]||'OLED'} · OLED`},[route.view]);
 const groups=[{label:'Atendimento',items:[['dashboard','Visão geral',LayoutDashboard],['orders','Ordens de serviço',ClipboardList],['customers','Clientes',Users],['devices','Aparelhos',Smartphone],['screens','Preços de telas',MonitorSmartphone]]},...(user.role==='ADMIN'?[{label:'Gestão',items:[['products','Estoque',Package],['suppliers','Fornecedores',Truck],['payments','Pagamentos',Wallet],['reports','Relatórios',ChartNoAxesCombined]]},{label:'Administração',items:[['users','Equipe',Users],['audit','Auditoria',ShieldCheck]]}]:[])];
 const go=(view:string,id='')=>navigate({view,id});const {view,id}=route;
 return <div className={`app ${collapsed?'sidebar-is-collapsed':''}`}><a className="skip-link" href="#main-content">Pular para o conteúdo</a><aside ref={sidebar} id="primary-navigation" className={`sidebar ${mobile?'visible':''}`} aria-label="Navegação principal"><div className="side-logo"><a className="wordmark" href="#dashboard" aria-label="OLED, visão geral" onClick={e=>{e.preventDefault();go('dashboard')}}><span className="brand-symbol"><Smartphone size={23}/></span><span className="brand-name">OLED<small>ASSISTÊNCIA</small></span></a><button className="icon mobile-only" aria-label="Fechar menu" onClick={()=>setMobile(false)}><X size={20}/></button></div><div className="workspace-name"><span className="workspace-icon">O</span><div>Assistência técnica<small>Espaço de trabalho</small></div></div><nav>{groups.map(group=><section className="nav-group" key={group.label}><h2 className="nav-label">{group.label}</h2>{group.items.map(([v,label,Icon]:any)=><button key={v} title={collapsed?label:undefined} aria-label={label} aria-current={view===v||(view==='detail'&&v==='orders')?'page':undefined} className={view===v||(view==='detail'&&v==='orders')?'active':''} onClick={()=>go(v)}><Icon size={18}/><span className="nav-text">{label}</span></button>)}</section>)}</nav><div className="sidebar-bottom"><button className={view==='settings'?'active':''} title={collapsed?'Configurações':undefined} aria-label="Configurações" aria-current={view==='settings'?'page':undefined} onClick={()=>go('settings')}><SettingsIcon size={18}/><span className="nav-text">Configurações</span></button><button className="collapse-toggle" aria-label={collapsed?'Expandir menu':'Recolher menu'} title={collapsed?'Expandir menu':'Recolher menu'} aria-expanded={!collapsed} onClick={()=>setCollapsed(!collapsed)}>{collapsed?<PanelLeftOpen size={18}/>:<PanelLeftClose size={18}/>}<span className="nav-text">Recolher menu</span></button><div className="profile"><div className="avatar">{user.name.slice(0,2).toUpperCase()}</div><div className="profile-copy"><strong title={user.name}>{user.name}</strong><small>{roleNames[user.role]}</small></div><button className="icon" title="Sair" aria-label="Sair" disabled={loggingOut} onClick={async()=>{setLoggingOut(true);try{await post('/auth/logout');clearViewMemory();logout()}catch(e:any){toast(e.message,'error')}finally{setLoggingOut(false)}}}><LogOut size={17}/></button></div></div></aside>{mobile&&<button className="sidebar-backdrop" aria-label="Fechar navegação" onClick={()=>setMobile(false)}/>}
  <div className="main-shell" inert={mobile||undefined}><header className="topbar"><button ref={menuButton} className="icon mobile-only" aria-label="Abrir menu" aria-expanded={mobile} aria-controls="primary-navigation" onClick={()=>setMobile(true)}><Menu size={20}/></button><div className="breadcrumb"><span>Workspace</span><ChevronRight size={14}/><strong>{denied?'Acesso negado':labels[view]}</strong></div><GlobalSearch navigate={navigate}/><div className="topbar-right"><Button className="quick-order" onClick={()=>setNewOrder(true)} title="Nova OS · Ctrl Alt N"><Plus size={17}/><span>Nova OS</span></Button><button className="icon" aria-label="Notificações" title="Notificações" onClick={()=>go('notifications')}><Bell size={19}/></button><button className="avatar avatar-button" title={`${user.name} · ${roleNames[user.role]}`} aria-label="Meu perfil e configurações" onClick={()=>go('settings')}>{user.name.slice(0,1).toUpperCase()}</button></div></header>
  <main className="content" id="main-content" tabIndex={-1} ref={content}><div className="page-transition" key={denied||view}>{denied?<><div className="page-heading"><div><span className="overline">ACESSO NEGADO</span><h1 tabIndex={-1}>Você não tem permissão para acessar {labels[denied]||'esta área'}</h1><p>Esta rota é restrita a administradores. Você foi mantido em uma área segura do sistema.</p></div></div><Empty title="Área administrativa" detail="Se precisar desse acesso, solicite a um administrador da assistência." action={<Button onClick={()=>setDenied('')}>Ir para visão geral</Button>}/></>:view==='dashboard'?<Dashboard user={user} navigate={go} newOrder={()=>setNewOrder(true)}/>:view==='orders'?<OrdersList key={id} initialStatus={id} open={id=>go('detail',id)} newOrder={()=>setNewOrder(true)}/>:view==='detail'?<OrderDetail key={id} id={id} user={user} back={()=>go('orders')} open={id=>go('detail',id)}/>:view==='reports'?<Reports/>:view==='settings'?<Settings user={user}/>:<Catalog key={`${view}:${route.search||''}`} view={view} user={user} openOrder={id=>go('detail',id)} initialId={id} initialSearch={route.search||''}/>}</div><footer className="app-footer"><span>OLED · Gestão da assistência</span><span>Atalho: <kbd>Ctrl K</kbd> para buscar</span></footer></main></div><ToastRegion/>{newOrder&&<NewOrder user={user} close={()=>setNewOrder(false)} created={id=>{setNewOrder(false);go('detail',id)}}/>}</div>;
}
