'use client';
import {useEffect,useRef,useState} from 'react';import {Search,X,ArrowUpRight} from 'lucide-react';
import {money} from '../lib/api';import {useDebounced,useQuery} from '../lib/use-query';import type {AppRoute} from '../lib/navigation';import {Badge,Empty} from './ui';

export default function GlobalSearch({navigate}:{navigate:(r:AppRoute)=>void}){
 const [text,setText]=useState(''),[open,setOpen]=useState(false);const debounced=useDebounced(text.trim());const query=useQuery<any>(open&&debounced.length>=2?`/search?q=${encodeURIComponent(debounced)}`:null);const ref=useRef<HTMLDivElement>(null),input=useRef<HTMLInputElement>(null);
 useEffect(()=>{const shortcut=(e:KeyboardEvent)=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();input.current?.focus();setOpen(true)}};const outside=(e:PointerEvent)=>{if(!ref.current?.contains(e.target as Node))setOpen(false)};window.addEventListener('keydown',shortcut);document.addEventListener('pointerdown',outside);return()=>{window.removeEventListener('keydown',shortcut);document.removeEventListener('pointerdown',outside)}},[]);
 const go=(route:AppRoute)=>{setOpen(false);setText('');navigate(route)};const results=query.data;const hasResults=!!(results?.orders?.length||results?.customers?.length||results?.devices?.length||results?.products?.length);
 return <div className="global-search" ref={ref} role="search" onKeyDown={e=>{if(e.key==='Escape'){setOpen(false);input.current?.focus()}if(e.key==='ArrowDown'||e.key==='ArrowUp'){const items=Array.from(ref.current!.querySelectorAll<HTMLButtonElement>('.search-results button'));if(!items.length)return;e.preventDefault();const current=items.indexOf(document.activeElement as HTMLButtonElement);items[(current+(e.key==='ArrowDown'?1:-1)+items.length)%items.length]?.focus()}}}><Search size={17} aria-hidden="true"/><input ref={input} type="search" role="combobox" aria-label="Busca global" aria-expanded={open} aria-controls="global-results" aria-haspopup="listbox" aria-autocomplete="list" placeholder="Buscar no sistema…" value={text} onFocus={()=>setOpen(true)} onChange={e=>{setText(e.target.value);setOpen(true)}}/>{text?<button type="button" className="icon" aria-label="Limpar busca global" onClick={()=>{setText('');input.current?.focus()}}><X size={15}/></button>:<kbd aria-hidden="true">Ctrl K</kbd>}{open&&<div className="search-results" id="global-results" aria-label="Resultados da busca global">{text.trim().length<2?<p className="search-help">Busque por OS, cliente, telefone, aparelho ou SKU.</p>:query.pending?<p role="status" className="search-help">Buscando…</p>:query.error?<p className="search-help" role="alert">{query.error}</p>:results&&<>{results.orders?.length>0&&<><h3>Ordens de serviço</h3>{results.orders.map((o:any)=><button type="button" key={o.id} onClick={()=>go({view:'detail',id:o.id})}><span><strong>#{o.number} · {o.customer.name}</strong><small>{o.device.model}</small></span><Badge status={o.status}/></button>)}</>}{results.customers?.length>0&&<><h3>Clientes</h3>{results.customers.map((c:any)=><button type="button" key={c.id} onClick={()=>go({view:'customers',id:c.id})}><span>{c.name}<small>{c.phone}</small></span><ArrowUpRight size={16}/></button>)}</>}{results.devices?.length>0&&<><h3>Aparelhos</h3>{results.devices.map((d:any)=><button type="button" key={d.id} onClick={()=>go({view:'devices',id:d.id})}><span>{d.brand} {d.model}</span><ArrowUpRight size={16}/></button>)}</>}{results.products?.length>0&&<><h3>Peças e telas</h3>{results.products.map((p:any)=><button type="button" key={p.id} onClick={()=>go({view:'products',id:p.id})}><span>{p.name}<small>{p.sku} · {money(p.priceCents)}</small></span><ArrowUpRight size={16}/></button>)}</>}{!hasResults&&<Empty title="Nenhum resultado" detail="Tente buscar por outro termo."/>}</>}</div>}</div>;
}
