'use client';
import { Children, cloneElement, isValidElement, useCallback, useEffect, useId, useRef, useState, type ButtonHTMLAttributes, type ReactNode, type ReactElement } from 'react';
import { AlertCircle, CheckCircle2, ChevronLeft, ChevronRight, Inbox, Info, LoaderCircle, MoreHorizontal, Search, X } from 'lucide-react';
import { statuses } from '../lib/api';

export function Button({variant='secondary',busy=false,children,className='',disabled,...props}:ButtonHTMLAttributes<HTMLButtonElement>&{variant?:'primary'|'secondary'|'ghost'|'danger';busy?:boolean}) {
 return <button type="button" {...props} className={`button ${variant} ${className}`} disabled={disabled||busy} aria-busy={busy||undefined}>{busy&&<LoaderCircle size={16} className="spin" aria-hidden="true"/>}{children}</button>;
}
export function Badge({status}:{status:string}) {return <span className={`badge s-${status}`}>{statuses[status]||status}</span>}
export function Empty({title='Nenhum registro encontrado',detail='Os registros aparecerão aqui após o cadastro.',action}:{title?:string;detail?:string;action?:ReactNode}) {return <div className="empty"><span className="empty-icon"><Inbox size={25} aria-hidden="true"/></span><h3>{title}</h3><p>{detail}</p>{action&&<div className="empty-action">{action}</div>}</div>}
export function Skeleton({className=''}:{className?:string}){return <span aria-hidden="true" className={`skeleton ${className}`}/>}
export function PageSkeleton(){return <div className="page-skeleton" role="status" aria-label="Carregando conteúdo"><div className="page-heading"><div><Skeleton className="skeleton-title"/><Skeleton className="skeleton-description"/></div><Skeleton className="skeleton-button"/></div><div className="stats">{[1,2,3,4].map(i=><div className="panel" key={i}><Skeleton className="skeleton-line"/><Skeleton className="skeleton-value"/></div>)}</div><TableSkeleton/></div>}
export function TableSkeleton(){return <div className="table-skeleton" role="status" aria-label="Carregando registros">{[1,2,3,4,5].map(i=><div key={i}><Skeleton/><Skeleton/><Skeleton/></div>)}</div>}
export function Modal({title,children,onClose,wide=false,variant='modal',busy=false,protectChanges=true}:{title:string;children:ReactNode;onClose:()=>void;wide?:boolean;variant?:'modal'|'drawer';busy?:boolean;protectChanges?:boolean}) {
 const ref=useRef<HTMLDialogElement>(null),heading=useId();const [dirty,setDirty]=useState(false),[confirm,setConfirm]=useState(false);
 const requestClose=()=>{if(busy)return;if(dirty&&protectChanges){setConfirm(true);return}onClose()};
 useEffect(()=>{const previous=document.activeElement as HTMLElement|null;const dialog=ref.current;dialog?.showModal();const overflow=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{dialog?.close();document.body.style.overflow=overflow;previous?.focus()}},[]);
 useEffect(()=>{if(confirm)ref.current?.querySelector<HTMLButtonElement>('[data-keep-editing]')?.focus()},[confirm]);
 return <dialog aria-labelledby={heading} ref={ref} className={`modal ${wide?'wide':''} ${variant==='drawer'?'drawer':''}`} onCancel={e=>{e.preventDefault();if(confirm)setConfirm(false);else requestClose()}} onClick={e=>{if(e.target===ref.current){const r=ref.current!.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)requestClose()}}}>
 <header><div><span className="overline">OLED · ATENDIMENTO</span><h2 id={heading}>{title}</h2></div><button type="button" className="icon" onClick={requestClose} disabled={busy} aria-label="Fechar"><X size={20}/></button></header>
 {confirm?<section className="discard-confirm" role="alertdialog" aria-labelledby={`${heading}-discard`}><AlertCircle size={28}/><h3 id={`${heading}-discard`}>Descartar alterações?</h3><p>Os dados ainda não enviados serão perdidos. Os cadastros já salvos serão mantidos.</p><div className="actions"><Button data-keep-editing onClick={()=>setConfirm(false)}>Continuar editando</Button><Button variant="danger" onClick={onClose}>Descartar e fechar</Button></div></section>:null}
 <div className="modal-body" hidden={confirm} onInputCapture={()=>setDirty(true)}>{children}</div>
 {!confirm&&<footer className="modal-footer"><small>{busy?'Aguarde a conclusão da operação.':'Esc para fechar'}</small><Button onClick={requestClose} disabled={busy}>Cancelar</Button></footer>}
 </dialog>;
}
function validationMessage(el:HTMLInputElement|HTMLSelectElement|HTMLTextAreaElement){const v=el.validity;if(v.valid)return '';if(v.valueMissing)return 'Preencha este campo.';if(v.typeMismatch)return 'Informe um e-mail válido.';if(v.tooShort)return `Use pelo menos ${(el as HTMLInputElement).minLength} caracteres.`;if(v.rangeUnderflow)return `O valor mínimo é ${(el as HTMLInputElement).min}.`;if(v.rangeOverflow)return `O valor máximo é ${(el as HTMLInputElement).max}.`;if(v.stepMismatch)return 'Confira as casas decimais do valor.';if(v.patternMismatch)return el.getAttribute('data-format-hint')||'Confira o formato deste campo.';return 'Confira o valor informado.'}
export function Field({label,children,hint,error}:{label:string;children:ReactNode;hint?:string;error?:string}) {
 const key=useId(),[localError,setError]=useState(''),[touched,setTouched]=useState(false);const message=error||localError;const control=Children.only(children);let child=children;
 if(isValidElement(control)){const element=control as ReactElement<Record<string,any>>;const props=element.props;child=cloneElement(element,{id:props.id||key,'aria-invalid':message?true:undefined,'aria-describedby':[hint?`${key}-hint`:'',message?`${key}-error`:'',props['aria-describedby']||''].filter(Boolean).join(' ')||undefined,onBlur:(e:any)=>{props.onBlur?.(e);setTouched(true);setError(validationMessage(e.target))},onInvalid:(e:any)=>{props.onInvalid?.(e);e.preventDefault();setTouched(true);setError(validationMessage(e.target));if(e.target.form?.querySelector(':invalid')===e.target)e.target.focus()},onChange:(e:any)=>{props.onChange?.(e);if(touched)setError(validationMessage(e.target))}})}
 return <label className={`field ${message?'field-invalid':''}`}><span>{label}</span>{child}{message?<small className="field-error" id={`${key}-error`} role="alert">{message}</small>:null}{hint&&<small id={`${key}-hint`}>{hint}</small>}</label>;
}
export function ErrorBox({error,retry}:{error:string;retry?:()=>void}) {return error?<div role="alert" className="error"><AlertCircle size={18}/><span>{error}</span>{retry&&<Button onClick={retry}>Tentar novamente</Button>}</div>:null}
export function Submit({busy,children,busyLabel='Salvando…',danger=false}:{busy:boolean;children:ReactNode;busyLabel?:string;danger?:boolean}){return <Button type="submit" variant={danger?'danger':'primary'} busy={busy}>{busy?busyLabel:children}</Button>}
export function useAction(){const [busy,setBusy]=useState(false),[error,setError]=useState('');const pending=useRef(false);const run=useCallback(async(fn:()=>Promise<void>)=>{if(pending.current)return;pending.current=true;setError('');setBusy(true);try{await fn()}catch(e:any){if(e.name!=='AbortError')setError(e.message||'Não foi possível concluir. Tente novamente.')}finally{pending.current=false;setBusy(false)}},[]);return {busy,error,setError,run}}
export function PageHeader({title,description,eyebrow,actions}:{title:string;description?:string;eyebrow?:string;actions?:ReactNode}){return <div className="page-heading"><div>{eyebrow&&<span className="overline">{eyebrow}</span>}<h1 tabIndex={-1}>{title}</h1>{description&&<p>{description}</p>}</div>{actions&&<div className="page-actions">{actions}</div>}</div>}
export function SearchInput({value,onChange,label,placeholder='Buscar…'}:{value:string;onChange:(v:string)=>void;label:string;placeholder?:string}){return <div className="search-input"><Search size={18} aria-hidden="true"/><input type="search" aria-label={label} placeholder={placeholder} value={value} onChange={e=>onChange(e.target.value)}/>{value&&<button type="button" className="icon" aria-label={`Limpar ${label.toLowerCase()}`} onClick={()=>onChange('')}><X size={16}/></button>}</div>}
export function Pagination({page,total,pageSize=25,onChange,busy=false,hasNext}:{page:number;total?:number;pageSize?:number;onChange:(p:number)=>void;busy?:boolean;hasNext?:boolean}){const pages=total===undefined?undefined:Math.max(1,Math.ceil(total/pageSize));return <nav className="pagination" aria-label="Paginação"><span aria-live="polite">{total===undefined?`Página ${page}`:total===0?'Nenhum resultado':`${(page-1)*pageSize+1}–${Math.min(page*pageSize,total)} de ${total} registros`}</span><div><Button disabled={busy||page===1} onClick={()=>onChange(page-1)} aria-label="Página anterior"><ChevronLeft size={16}/><span>Anterior</span></Button><small>{page}{pages?` / ${pages}`:''}</small><Button disabled={busy||(pages? page>=pages:!hasNext)} onClick={()=>onChange(page+1)} aria-label="Próxima página"><span>Próxima</span><ChevronRight size={16}/></Button></div></nav>}
export function ActionMenu({label='Mais ações',children}:{label?:string;children:ReactNode}) {
 const id=useId();const trigger=useRef<HTMLButtonElement>(null),menu=useRef<HTMLDivElement>(null);const [open,setOpen]=useState(false);
 const place=()=>{const r=trigger.current?.getBoundingClientRect();if(r&&menu.current){const width=210;menu.current.style.left=Math.max(8,Math.min(r.right-width,window.innerWidth-width-8))+'px';menu.current.style.top=Math.min(r.bottom+6,window.innerHeight-menu.current.offsetHeight-8)+'px'}};
 useEffect(()=>{if(!open)return;place();menu.current?.querySelector<HTMLButtonElement>('button')?.focus();const close=()=>menu.current?.hidePopover();window.addEventListener('resize',close);window.addEventListener('scroll',close,true);return()=>{window.removeEventListener('resize',close);window.removeEventListener('scroll',close,true)}},[open]);
 return <div className="action-menu"><button type="button" ref={trigger} className="icon menu-trigger" aria-label={label} aria-expanded={open} popoverTarget={id}><MoreHorizontal size={19}/></button><div id={id} ref={menu} popover="auto" className="menu-popover" onToggle={e=>setOpen(e.newState==='open')} onKeyDown={e=>{if(['ArrowDown','ArrowUp','Home','End'].includes(e.key)){e.preventDefault();const buttons=Array.from(menu.current!.querySelectorAll<HTMLButtonElement>('button'));const current=buttons.indexOf(document.activeElement as HTMLButtonElement);const next=e.key==='Home'?0:e.key==='End'?buttons.length-1:(current+(e.key==='ArrowDown'?1:-1)+buttons.length)%buttons.length;buttons[next]?.focus()}}} onClick={()=>{menu.current?.hidePopover()}}>{children}</div></div>;
}
type Toast={id:number;message:string;type:'success'|'error'|'warning'|'info'};
export function toast(message:string,type:Toast['type']='success'){window.dispatchEvent(new CustomEvent('oled:toast',{detail:{message,type}}))}
export function ToastRegion(){const [items,setItems]=useState<Toast[]>([]);const timers=useRef<ReturnType<typeof setTimeout>[]>([]);useEffect(()=>{const listener=(e:Event)=>{const t=(e as CustomEvent).detail;const id=Date.now()+Math.random();setItems(v=>[...v.slice(-2),{...t,id}]);timers.current.push(setTimeout(()=>setItems(v=>v.filter(x=>x.id!==id)),5500))};window.addEventListener('oled:toast',listener);return()=>{window.removeEventListener('oled:toast',listener);timers.current.forEach(clearTimeout)}},[]);return <div className="toast-region" role="region" aria-label="Notificações de ações">{items.map(t=><div role={t.type==='error'?'alert':'status'} className={`toast toast-${t.type}`} key={t.id}>{t.type==='success'?<CheckCircle2 size={19}/>:t.type==='error'||t.type==='warning'?<AlertCircle size={19}/>:<Info size={19}/>}<span>{t.message}</span><button className="icon" aria-label="Dispensar notificação" onClick={()=>setItems(v=>v.filter(x=>x.id!==t.id))}><X size={16}/></button></div>)}</div>}
