// UI tests use controlled API responses; they do not replace backend integration tests.
const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');
const {chromium}=require('playwright-core');const AxeBuilder=require('@axe-core/playwright').default;
const {installFixtures,orders}=require('./fixtures.cjs');
const url=process.env.FRONTEND_TEST_URL||'http://127.0.0.1:3000';
const screenshots=path.resolve('reports/screenshots');fs.mkdirSync(screenshots,{recursive:true});
const results=[],errors=[];
async function main(){
 const browser=await chromium.launch({headless:true,executablePath:process.env.PLAYWRIGHT_EXECUTABLE_PATH||'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'});
 const context=await browser.newContext({viewport:{width:1440,height:1000},locale:'pt-BR',reducedMotion:'reduce'});
 const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));const requests=await installFixtures(page);
 const test=async(name,fn)=>{try{await fn();results.push({name,passed:true});console.log('PASS '+name)}catch(e){results.push({name,passed:false,error:e.message});console.error('FAIL '+name+': '+e.message);await page.screenshot({path:path.join(screenshots,'failure-'+results.length+'.png'),fullPage:true}).catch(()=>{})}};
 const route=async(hash)=>{await page.evaluate(h=>{window.location.hash=h},hash);await page.waitForFunction(()=>!document.querySelector('.page-skeleton,.table-skeleton'));await page.waitForTimeout(180)};
 const checkOverflow=async()=>{assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'Document has horizontal overflow')};
 await page.goto(url);await page.getByRole('heading',{name:'Visão geral',exact:true}).waitFor();
 await test('Dashboard com dados reais do contrato',async()=>{await page.getByText('R$ 12.680,00',{exact:true}).waitFor();assert.equal(await page.locator('.stat').count(),4)});
 await test('Sidebar recolhe e persiste após recarregar',async()=>{await page.getByRole('button',{name:'Recolher menu',exact:true}).click();assert.ok(await page.locator('.app').evaluate(el=>el.classList.contains('sidebar-is-collapsed')));await page.reload();await page.getByRole('heading',{name:'Visão geral',exact:true}).waitFor();assert.ok(await page.locator('.app').evaluate(el=>el.classList.contains('sidebar-is-collapsed')));await page.getByRole('button',{name:'Expandir menu',exact:true}).click()});
 await test('Filtro do dashboard abre a etapa correta',async()=>{await page.locator('.flow-row').filter({hasText:'Em reparo'}).click();await page.getByRole('combobox',{name:'Filtrar por status'}).waitFor();assert.equal(await page.getByRole('combobox',{name:'Filtrar por status'}).inputValue(),'REPAIR');await page.getByRole('button',{name:'Limpar filtros',exact:true}).click()});
 await test('Paginação, busca, detalhe e retorno preservam filtros',async()=>{await page.getByRole('button',{name:'Próxima página'}).click();await page.getByText('26–31 de 31 registros').waitFor();await page.getByRole('searchbox',{name:'Buscar ordens'}).fill('Marina');await page.getByText('1–25 de 31 registros').waitFor();await page.getByRole('button',{name:'Abrir OS 1045',exact:true}).click();await page.getByRole('heading',{name:'OS #1045',exact:true}).waitFor();await page.getByRole('button',{name:'Ordens de serviço',exact:true}).last().click();await page.getByRole('searchbox',{name:'Buscar ordens'}).waitFor();assert.equal(await page.getByRole('searchbox',{name:'Buscar ordens'}).inputValue(),'Marina')});
 await test('Busca vazia com ação de limpar',async()=>{await page.getByRole('searchbox',{name:'Buscar ordens'}).fill('nenhum-resultado');await page.getByRole('heading',{name:'Nenhuma OS com esses filtros'}).waitFor();await page.getByRole('button',{name:'Limpar filtros',exact:true}).last().click();await page.getByText('31 ordens encontradas').waitFor()});
 await test('Ctrl K e busca global abrem a OS diretamente',async()=>{await page.keyboard.press('Control+k');assert.equal(await page.getByRole('combobox',{name:'Busca global'}).evaluate(el=>document.activeElement===el),true);await page.getByRole('combobox',{name:'Busca global'}).fill('1045');await page.locator('.search-results button').first().waitFor();await page.keyboard.press('ArrowDown');await page.keyboard.press('Enter');await page.getByRole('heading',{name:'OS #1045',exact:true}).waitFor();assert.ok(page.url().includes(orders[0].id))});
 await test('Abas por teclado e peças somente ao abrir formulário',async()=>{assert.equal(requests.filter(r=>r.path==='/products').length,0);await page.getByRole('tab',{name:'Resumo',exact:true}).focus();await page.keyboard.press('ArrowRight');assert.equal(await page.getByRole('tab',{name:'Orçamento',exact:true}).getAttribute('aria-selected'),'true');await page.getByRole('button',{name:'Adicionar item',exact:true}).click();await page.getByRole('dialog').waitFor();await page.waitForTimeout(400);assert.equal(requests.filter(r=>r.path==='/products').length,1);await page.keyboard.press('Escape')});
 await test('Nova OS valida campos e protege alterações',async()=>{await page.keyboard.press('Control+Alt+n');await page.getByRole('dialog',{name:'Nova ordem de serviço'}).waitFor();await page.getByRole('button',{name:'+ Cadastrar novo cliente'}).click();await page.getByRole('button',{name:'Salvar e continuar',exact:true}).click();assert.ok(await page.locator('.field-error').count()>=2);await page.getByLabel(/^Nome \*/).fill('Cliente não salvo');await page.keyboard.press('Escape');await page.getByRole('heading',{name:'Descartar alterações?'}).waitFor();await page.getByRole('button',{name:'Continuar editando'}).click();assert.equal(await page.getByLabel(/^Nome \*/).inputValue(),'Cliente não salvo');await page.keyboard.press('Escape');await page.getByRole('button',{name:'Descartar e fechar'}).click();await page.getByRole('dialog').waitFor({state:'hidden'})});
 await test('Criação com checklist completo e rascunho preservado',async()=>{await page.keyboard.press('Control+Alt+n');await page.getByRole('textbox',{name:'Buscar cliente'}).fill('Marina');await page.getByRole('button',{name:/Marina Alves/}).click();await page.getByRole('heading',{name:'Qual aparelho será atendido?'}).waitFor();await page.getByRole('button',{name:'+ Novo aparelho'}).click();await page.getByLabel('Marca *',{exact:true}).fill('Motorola');await page.getByRole('button',{name:'Voltar',exact:true}).click();await page.getByRole('button',{name:/Marina Alves/}).click();assert.equal(await page.getByLabel('Marca *',{exact:true}).inputValue(),'Motorola');await page.getByRole('button',{name:/Samsung Galaxy A15/}).click();await page.getByLabel('Problema relatado *').fill('Tela sem imagem');await page.getByRole('button',{name:'Continuar para fotos'}).click();await page.getByRole('button',{name:'Voltar',exact:true}).click();assert.equal(await page.getByLabel('Problema relatado *').inputValue(),'Tela sem imagem');await page.getByRole('button',{name:'Continuar para fotos'}).click();await page.getByRole('button',{name:'Criar ordem de serviço',exact:true}).click();await page.getByRole('dialog').waitFor({state:'hidden'});const body=JSON.parse(requests.findLast(r=>r.path==='/service-orders'&&r.method==='POST').body);assert.equal(Object.keys(body.checklist).length,13);assert.equal(body.problem,'Tela sem imagem')});
 await test('Menu de ações e confirmação para desativar usuário',async()=>{await route('products');await page.getByRole('button',{name:'Ações de Tela Samsung Galaxy A15'}).click();await page.getByRole('button',{name:'Movimentar estoque',exact:true}).waitFor();const r=await page.locator('.menu-popover').boundingBox();assert.ok(r.x>=0&&r.x+r.width<=1440);await page.keyboard.press('Escape');await route('users');await page.getByRole('button',{name:'Desativar',exact:true}).click();await page.getByRole('dialog',{name:'Desativar usuário'}).waitFor();await page.keyboard.press('Escape');assert.equal(requests.filter(r=>r.method==='PATCH'&&r.path.startsWith('/users')).length,0)});
 const views=['dashboard','orders','customers','devices','screens','products','suppliers','payments','reports','users','audit','notifications','stock','settings','detail/'+orders[0].id];
 for(const width of [1920,1440,1366,1024,768,430,390])await test('Responsividade de 15 telas em '+width+'px',async()=>{await page.setViewportSize({width,height:1000});for(const view of views){await route(view);await checkOverflow();if(view.startsWith('detail/'))assert.ok(await page.getByRole('button',{name:'Registrar pagamento',exact:true}).isVisible(),'Payment not visible');}await route('dashboard');if([1440,768,390].includes(width))await page.screenshot({path:path.join(screenshots,'dashboard-'+width+'.png'),fullPage:true});await route('orders');if(width===390)await page.screenshot({path:path.join(screenshots,'ordens-390.png'),fullPage:true})});
 await test('Menu mobile contém o foco e fecha com ESC',async()=>{await page.getByRole('button',{name:'Abrir menu',exact:true}).click();assert.ok(await page.locator('.main-shell').getAttribute('inert')!==null);await page.keyboard.press('Escape');assert.ok(!(await page.locator('.sidebar').evaluate(el=>el.classList.contains('visible'))))});
 await test('Acessibilidade automatizada das telas e formulário',async()=>{await page.setViewportSize({width:1440,height:1000});const violations=[];for(const view of ['dashboard','orders','products','settings','detail/'+orders[0].id]){await route(view);const scan=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze();for(const v of scan.violations)violations.push({view,id:v.id,impact:v.impact,nodes:v.nodes.map(n=>({html:n.html,summary:n.failureSummary}))})}await page.keyboard.press('Control+Alt+n');const scan=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze();violations.push(...scan.violations.map(v=>({view:'new-order',id:v.id,nodes:v.nodes.map(n=>({html:n.html,summary:n.failureSummary}))})));await page.keyboard.press('Escape');fs.writeFileSync(path.resolve('reports/accessibility-results.json'),JSON.stringify(violations,null,2));assert.equal(violations.length,0,JSON.stringify(violations.map(v=>({view:v.view,id:v.id}))))});
 await test('Erro de API permite tentar novamente',async()=>{const p=await context.newPage();await installFixtures(p,{failOrders:true});await p.goto(url+'/#orders');await p.getByRole('button',{name:'Tentar novamente'}).click();await p.getByText('31 ordens encontradas').waitFor();await p.close()});
 for(const role of ['TECHNICIAN','ATTENDANT'])await test('Visibilidade das ações para '+role,async()=>{const p=await context.newPage();await installFixtures(p,{role});await p.goto(url+'/#detail/'+orders[0].id);await p.getByRole('heading',{name:'OS #1045',exact:true}).waitFor();assert.equal(await p.locator('.sidebar').getByRole('button',{name:'Relatórios',exact:true}).count(),0);assert.equal(await p.getByRole('button',{name:'Consultar PIN',exact:true}).count(),role==='TECHNICIAN'?1:0);assert.equal(await p.getByRole('button',{name:'Registrar pagamento',exact:true}).count(),role==='ATTENDANT'?1:0);await p.close()});
 await test('Nenhum erro JavaScript durante os fluxos',async()=>assert.deepEqual(errors,[]));
 fs.writeFileSync(path.resolve('reports/browser-results.json'),JSON.stringify({date:new Date().toISOString(),mode:'controlled API fixtures',browser:'Microsoft Edge headless',results,errors},null,2));await browser.close();if(results.some(r=>!r.passed))process.exitCode=1;
}
main().catch(e=>{console.error(e);process.exitCode=1});
