// Browser-test fixtures only. This file is not imported or shipped by the application.
const customer={id:'11111111-1111-4111-8111-111111111111',name:'Marina Alves',phone:'11987654321',cpf:'',email:'',address:'',notes:''};
const device={id:'22222222-2222-4222-8222-222222222222',customerId:customer.id,brand:'Samsung',model:'Galaxy A15',color:'Azul',imei:'123456789012345',customer};
const technician={id:'33333333-3333-4333-8333-333333333333',name:'Rafael',role:'ADMIN',email:'admin@example.test',active:true,mustChangePassword:false};
const product={id:'44444444-4444-4444-8444-444444444444',name:'Tela Samsung Galaxy A15',sku:'TEL-A15-OLED',category:'Telas',brand:'Samsung',model:'Galaxy A15',screenType:'OLED',quality:'Premium',supplierId:null,supplier:null,costCents:15000,saleCents:32000,installationCents:8000,stock:3,minStock:2,location:'A1',notes:'',active:true};
const statuses=['OPEN','ANALYSIS','REPAIR','AWAITING_PICKUP','AWAITING_PART','AWAITING_APPROVAL'];
const orders=Array.from({length:31},(_,i)=>({id:`55555555-5555-4555-8555-${String(i+1).padStart(12,'0')}`,number:1045-i,customerId:customer.id,deviceId:device.id,customer,device,technician,technicianId:technician.id,status:statuses[i%statuses.length],problem:'Tela com trinca após queda. Verificar resposta do toque.',physicalState:'Trinca no canto inferior; tampa traseira preservada.',notes:'Cliente prefere contato por WhatsApp.',diagnosis:'Substituição do módulo da tela.',accessories:['Aparelho','Capinha'],checklist:{Tela:'DANIFICADO'},createdAt:'2026-09-16T13:00:00Z',updatedAt:'2026-09-16T14:00:00Z',completedAt:null,deliveredAt:null,finalCents:40000,estimatedCents:40000,warrantyDays:90,termsSnapshot:'Termos de teste de interface.',photos:[],items:[{id:'item-1',type:'SERVICE',description:'Troca de tela',quantity:1,unitCents:40000}],budget:{status:'PENDING',discountCents:0,totalCents:40000},payments:[],history:[{id:'history-1',note:'Ordem de serviço aberta',userName:'Rafael',createdAt:'2026-09-16T13:00:00Z',previousStatus:'OPEN',newStatus:'OPEN'}],warranty:null,warrantyOrders:[]}));
const settings={name:'OLED Assistência Técnica',logo:'',cnpj:'',phone:'1130000000',whatsapp:'',address:'',hours:'',terms:'Termos da assistência.',warrantyDays:90,orderPrefix:'OS',printCopies:1};
async function installFixtures(page,{role='ADMIN',failOrders=false,delay=40}={}){const requests=[];let fail=failOrders;await page.route('**/api/**',async route=>{const req=route.request();const url=new URL(req.url());const p=url.pathname.replace('/api','');requests.push({path:p,query:url.search,method:req.method(),body:req.postData()});await new Promise(r=>setTimeout(r,delay));let data={};
if(p==='/auth/me')data={...technician,role};else if(p==='/dashboard')data={counts:Object.fromEntries(statuses.map(s=>[s,orders.filter(o=>o.status===s).length])),recent:orders.slice(0,6),revenueCents:1268000,lowStock:[{...product,stock:1}],partsUsed:24,services:[{description:'Troca de tela',_sum:{quantity:18}},{description:'Troca de bateria',_sum:{quantity:9}}],technicians:[{name:'Rafael',count:22},{name:'Ana',count:9}]};
else if(p==='/service-orders'&&req.method()==='GET'){if(fail){fail=false;return route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({message:'Não foi possível carregar as ordens. Tente novamente.'})})}const search=(url.searchParams.get('search')||'').toLowerCase(),status=url.searchParams.get('status');const list=orders.filter(o=>(!status||o.status===status)&&(!search||`${o.number} ${o.customer.name} ${o.device.model}`.toLowerCase().includes(search)));const current=Number(url.searchParams.get('page')||1);data={items:list.slice((current-1)*25,current*25),total:list.length};}
else if(p==='/service-orders'&&req.method()==='POST')data={...orders[0],id:orders[0].id};
else if(p.startsWith('/service-orders/'))data=orders.find(o=>p===`/service-orders/${o.id}`)||{ok:true};
else if(p==='/search')data={orders:orders.slice(0,2),customers:[customer],devices:[device],products:[product]};
else if(p==='/technicians')data=[technician];else if(p.startsWith('/settings'))data=settings;
else if(p==='/customers')data=req.method()==='POST'?{customer,existing:false}:{items:[customer],total:1};
else if(p.startsWith('/customers/'))data={...customer,devices:[device],orders:orders.slice(0,3)};
else if(p==='/devices')data=req.method()==='POST'?device:{items:[device],total:1};else if(p.startsWith('/devices/'))data={...device,orders:orders.slice(0,3)};
else if(p==='/products'||p==='/screens')data={items:[product],total:1};else if(p==='/suppliers')data=[{id:'66666666-6666-4666-8666-666666666666',name:'Distribuidora de teste',company:'Peças',phone:'1130000000',email:'',notes:''}];
else if(p==='/users')data=[{...technician,role},{id:'77777777-7777-4777-8777-777777777777',name:'Ana',email:'ana@example.test',role:'TECHNICIAN',active:true}];
else if(p==='/stock')data={items:[{id:'stock-1',product,kind:'ENTRY',quantity:5,balance:5,note:'Reposição',createdAt:'2026-09-16T13:00:00Z'}]};
else if(p==='/payments')data={items:[{id:'pay-1',orderId:orders[0].id,order:orders[0],amountCents:20000,method:'PIX',createdAt:'2026-09-16T13:00:00Z'}]};
else if(p==='/audit')data={items:[{id:'audit-1',action:'Ordem de serviço aberta',userName:'Rafael',entity:'ServiceOrder',entityId:orders[0].id,createdAt:'2026-09-16T13:00:00Z'}],total:1};
else if(p==='/notifications')data={items:[{id:'notification-1',message:'OS #1045 criada.',orderId:orders[0].id,createdAt:'2026-09-16T13:00:00Z'}]};
else if(p==='/reports')data={orders:orders.slice(0,4),total:4,truncated:false,revenueCents:160000,stock:[product]};
await route.fulfill({status:200,contentType:'application/json',body:JSON.stringify(data)});
});return requests;}
module.exports={installFixtures,orders,customer,device,product};
